language: rust

cache:
  - cargo

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)
  - cargo install-update -a

script:
  - echo -n "doc.colosseum.cf" > CNAME
  - mdbook build doc && mdbook test doc

deploy:
  provider: pages
  strategy: git
  edge: true
  cleanup: false
  github-token: $GITHUB_TOKEN
  local-dir: doc/book
  keep-history: false
  on:
    branch: master
  target_branch: gh-pages
