[book]
authors = ["Dario Ostuni"]
language = "en"
multilingual = false
src = "src"
title = "Code Colosseum"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
mathjax-support = true
git-repository-url = "https://github.com/dariost/CodeColosseum"
